spring.application.name=optical-shop
# 1. Connection URL (Notice we stop at /neondb)
spring.datasource.url=jdbc:postgresql://ep-aged-dust-a11p91gf-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

# 2. Credentials (Extracted from your string)
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# 3. Driver & JPA settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect